id: P003281
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD45099
  title: ནུབ་བྱང་མི་རིགས་སློབ་གྲྭ་ཆེན་མོའི་རིག་གཞུང་དུས་དེབ
  author: ''
  volumes:
    798cd3b9fcce475ca7700cc4120cda71:
      image_group_id: I2DB57121
      title: ''
      volume_number: 1
      total_pages: 0
    f8e01b06ab7a4c36991700229ce61647:
      image_group_id: I2DB57122
      title: ''
      volume_number: 2
      total_pages: 0
    bf2c2bbd79e64a12860d352475a91817:
      image_group_id: I2DB57123
      title: ''
      volume_number: 3
      total_pages: 0
    7ac9f8c022eb4506b16531ec465c06e8:
      image_group_id: I2DB57124
      title: ''
      volume_number: 4
      total_pages: 0
    54a33c947fb54c08b4efcf216b29d94c:
      image_group_id: I2DB57125
      title: ''
      volume_number: 5
      total_pages: 0
    654e01624f2c42a99738435bb9d099fb:
      image_group_id: I2DB57126
      title: ''
      volume_number: 6
      total_pages: 0
    68d501fba58a47f0bd884c41eedbc0ae:
      image_group_id: I2DB57127
      title: ''
      volume_number: 7
      total_pages: 100
      base_file: v001.txt
    6cd6f833f784461980a6ea848dbe0a34:
      image_group_id: I2DB57128
      title: ''
      volume_number: 8
      total_pages: 74
      base_file: v002.txt
    97ae6679eaac4582a7263c4b61b3cfca:
      image_group_id: I2DB57129
      title: ''
      volume_number: 9
      total_pages: 94
      base_file: v003.txt
    319ea06fe14a4ba68eaed8d22dc57c22:
      image_group_id: I2DB57130
      title: ''
      volume_number: 10
      total_pages: 0
    c26e63682b844c84a7cf615ab99d4111:
      image_group_id: I2DB57131
      title: ''
      volume_number: 11
      total_pages: 134
      base_file: v004.txt
    dd24575b07864e2cab0af02fe1c6cbaa:
      image_group_id: I2DB57132
      title: ''
      volume_number: 12
      total_pages: 94
      base_file: v005.txt
    82ed5c65e5c247a9adbcb1ffd77986df:
      image_group_id: I2DB57133
      title: ''
      volume_number: 13
      total_pages: 102
      base_file: v006.txt
    4c4bf95de2d84efca1815734b94bc7d0:
      image_group_id: I2DB57134
      title: ''
      volume_number: 14
      total_pages: 100
      base_file: v007.txt
    cee420b32b5b4059905d39658491017e:
      image_group_id: I2DB57135
      title: ''
      volume_number: 15
      total_pages: 86
      base_file: v008.txt
    c80de872efd04750aee5a1f6a1f556aa:
      image_group_id: I2DB57136
      title: ''
      volume_number: 16
      total_pages: 0
    74de3e8cd182421d92a39551deced543:
      image_group_id: I2DB57137
      title: ''
      volume_number: 17
      total_pages: 94
      base_file: v009.txt
    61da792549104b52b6e2691cc82fa2cb:
      image_group_id: I2DB57138
      title: ''
      volume_number: 18
      total_pages: 102
      base_file: v010.txt
    3baa102bfc4040c888f787cf24feb620:
      image_group_id: I2DB57139
      title: ''
      volume_number: 19
      total_pages: 100
      base_file: v011.txt
    9597423e867243d3823a8caab6f36cfc:
      image_group_id: I2DB57140
      title: ''
      volume_number: 20
      total_pages: 104
      base_file: v012.txt
    a8779baee42046f688bc6ab6339fd404:
      image_group_id: I2DB57141
      title: ''
      volume_number: 21
      total_pages: 96
      base_file: v013.txt
    783d4428a9534978a1bd51e7d1ace033:
      image_group_id: I2DB57142
      title: ''
      volume_number: 22
      total_pages: 102
      base_file: v014.txt
    9dcf08088dce4c018728dc8f6d4cbf2b:
      image_group_id: I2DB57143
      title: ''
      volume_number: 23
      total_pages: 108
      base_file: v015.txt
    5749879dcca241ebb420ce56e7f74831:
      image_group_id: I2DB57144
      title: ''
      volume_number: 24
      total_pages: 112
      base_file: v016.txt
    7dbe773d72324e6991b5082dadb98b6a:
      image_group_id: I2DB57145
      title: ''
      volume_number: 25
      total_pages: 102
      base_file: v017.txt
    8a587dce61764d42b301ee941b1a58f9:
      image_group_id: I2DB57146
      title: ''
      volume_number: 26
      total_pages: 102
      base_file: v018.txt
    e501a0dbb50f4924bc0bd0e9946809d0:
      image_group_id: I2DB57147
      title: ''
      volume_number: 27
      total_pages: 102
      base_file: v019.txt
    db26cda489aa4bd5ba60522730495c29:
      image_group_id: I2DB57148
      title: ''
      volume_number: 28
      total_pages: 102
      base_file: v020.txt
    34ac559abc594d849b01028ea03784ef:
      image_group_id: I2DB57149
      title: ''
      volume_number: 29
      total_pages: 0
    bd19881f4a994a9a8146554f648ed877:
      image_group_id: I2DB57150
      title: ''
      volume_number: 30
      total_pages: 102
      base_file: v021.txt
    7da7784fd0e34a6ab9c4f47225b629b7:
      image_group_id: I2DB57151
      title: ''
      volume_number: 31
      total_pages: 118
      base_file: v022.txt
    329ec9506aeb4f99a6306eff73594e37:
      image_group_id: I2DB57152
      title: ''
      volume_number: 32
      total_pages: 102
      base_file: v023.txt
    fcc35ffad129414db2b15a9778006a90:
      image_group_id: I2DB57153
      title: ''
      volume_number: 33
      total_pages: 102
      base_file: v024.txt
    70fbf161fc7e49ca8db7e8deb129c2ca:
      image_group_id: I2DB57154
      title: ''
      volume_number: 34
      total_pages: 0
    07fd2bece44a49478e6aa9123fcc837a:
      image_group_id: I2DB57155
      title: ''
      volume_number: 35
      total_pages: 0
    ca7372e0b8214890a219fa24acb71e93:
      image_group_id: I2DB57156
      title: ''
      volume_number: 36
      total_pages: 0
    d48de2d58b634c7ba2218348d596bf7f:
      image_group_id: I2DB57157
      title: ''
      volume_number: 37
      total_pages: 0
    fd4b3446b77a45de87e1fb346595f257:
      image_group_id: I2DB57158
      title: ''
      volume_number: 38
      total_pages: 0
    31e34207e6034934af591b24f21ca793:
      image_group_id: I2DB57159
      title: ''
      volume_number: 39
      total_pages: 0
    709e7bb09c894fdebdbfdde2ac97b017:
      image_group_id: I2DB57160
      title: ''
      volume_number: 40
      total_pages: 0
    1919a687f8cd478c8d65c81761cf0689:
      image_group_id: I2DB57161
      title: ''
      volume_number: 41
      total_pages: 0
    7c208668937048d995d722ee80f23e10:
      image_group_id: I2DB57162
      title: ''
      volume_number: 42
      total_pages: 0
    7731c9a46a354cb29a2fa88fba5662ec:
      image_group_id: I2DB57163
      title: ''
      volume_number: 43
      total_pages: 0
    1a540c34762843a6bac3ec77fa294b3c:
      image_group_id: I2DB57164
      title: ''
      volume_number: 44
      total_pages: 0
