id: I3C9C8441
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T17:46:11+00:00'
last_modified: '2022-06-07T18:49:47.050964+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD45099
  title: ནུབ་བྱང་མི་རིགས་སློབ་གྲྭ་ཆེན་མོའི་རིག་གཞུང་དུས་དེབ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    D4B8:
      image_group_id: I2DB57121
      title: ''
      total_pages: 0
      order: 1
      base_file: D4B8.txt
    D169:
      image_group_id: I2DB57122
      title: ''
      total_pages: 0
      order: 2
      base_file: D169.txt
    F4F0:
      image_group_id: I2DB57123
      title: ''
      total_pages: 0
      order: 3
      base_file: F4F0.txt
    079C:
      image_group_id: I2DB57124
      title: ''
      total_pages: 0
      order: 4
      base_file: 079C.txt
    DB68:
      image_group_id: I2DB57125
      title: ''
      total_pages: 0
      order: 5
      base_file: DB68.txt
    005F:
      image_group_id: I2DB57126
      title: ''
      total_pages: 0
      order: 6
      base_file: 005F.txt
    '7326':
      image_group_id: I2DB57127
      title: ''
      total_pages: 100
      order: 7
      base_file: 7326.txt
    55B2:
      image_group_id: I2DB57128
      title: ''
      total_pages: 74
      order: 8
      base_file: 55B2.txt
    F393:
      image_group_id: I2DB57129
      title: ''
      total_pages: 94
      order: 9
      base_file: F393.txt
    '4474':
      image_group_id: I2DB57130
      title: ''
      total_pages: 0
      order: 10
      base_file: 4474.txt
    139A:
      image_group_id: I2DB57131
      title: ''
      total_pages: 134
      order: 11
      base_file: 139A.txt
    67C4:
      image_group_id: I2DB57132
      title: ''
      total_pages: 94
      order: 12
      base_file: 67C4.txt
    641B:
      image_group_id: I2DB57133
      title: ''
      total_pages: 102
      order: 13
      base_file: 641B.txt
    '7849':
      image_group_id: I2DB57134
      title: ''
      total_pages: 100
      order: 14
      base_file: 7849.txt
    23C9:
      image_group_id: I2DB57135
      title: ''
      total_pages: 86
      order: 15
      base_file: 23C9.txt
    96B1:
      image_group_id: I2DB57136
      title: ''
      total_pages: 0
      order: 16
      base_file: 96B1.txt
    DA4B:
      image_group_id: I2DB57137
      title: ''
      total_pages: 94
      order: 17
      base_file: DA4B.txt
    442D:
      image_group_id: I2DB57138
      title: ''
      total_pages: 102
      order: 18
      base_file: 442D.txt
    E99B:
      image_group_id: I2DB57139
      title: ''
      total_pages: 100
      order: 19
      base_file: E99B.txt
    BAE2:
      image_group_id: I2DB57140
      title: ''
      total_pages: 104
      order: 20
      base_file: BAE2.txt
    FC15:
      image_group_id: I2DB57141
      title: ''
      total_pages: 96
      order: 21
      base_file: FC15.txt
    3A4C:
      image_group_id: I2DB57142
      title: ''
      total_pages: 102
      order: 22
      base_file: 3A4C.txt
    AA60:
      image_group_id: I2DB57143
      title: ''
      total_pages: 108
      order: 23
      base_file: AA60.txt
    25E6:
      image_group_id: I2DB57144
      title: ''
      total_pages: 112
      order: 24
      base_file: 25E6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
